@host=localhost:3005/agent/api/v1
######################################################
# Применение новых настроек
POST http://{{host}}/ping

{
    "Version": 1,
    "Ping": {
        "AgentVersion": "0.0.0",
        "AgentID": "abcd"
    }
}

###
